# Generated by Django 5.2.5 on 2025-08-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Concluído', 'Concluído'), ('Pendente', 'Pendente')], default='Pendente', max_length=20)),
                ('cliente', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_fim_prevista', models.DateField()),
            ],
        ),
    ]
