# Generated by Django 5.2.5 on 2025-08-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_previsao_termino', models.DateField()),
                ('status', models.CharField(choices=[('Planejamento', 'Planejamento'), ('Em Andamento', 'Em Andamento'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Planejamento', max_length=20)),
                ('cliente_id', models.IntegerField()),
                ('arquiteto_responsavel_id', models.IntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
